<a href="https://colab.research.google.com/github/rm30beau/Boosh/blob/master/PCAproject_RyanBeauchesne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

Saving students-performance-in-exams.zip to students-performance-in-exams (2).zip


In [111]:
data=pd.read_csv("students-performance-in-exams.zip") #reads the content of the file into a pandas dataframe called "
data.head()

gender race/ethnicity  ... reading score writing score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [123]:
newData = (data.drop(columns=['gender','race/ethnicity','parental level of education','lunch','test preparation course']))
print(X)

     math score  reading score  writing score
0            72             72             74
1            69             90             88
2            90             95             93
3            47             57             44
4            76             78             75
..          ...            ...            ...
995          88             99             95
996          62             55             55
997          59             71             65
998          68             78             77
999          77             86             86

[1000 rows x 3 columns]


In [0]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(newData)

In [118]:
import numpy as np
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

Covariance matrix 
[[1.001001   0.81839806 0.80344549]
 [0.81839806 1.001001   0.95555363]
 [0.80344549 0.95555363 1.001001  ]]


In [119]:
print('NumPy covariance matrix: \n%s' %np.cov(X_std.T))

NumPy covariance matrix: 
[[1.001001   0.81839806 0.80344549]
 [0.81839806 1.001001   0.95555363]
 [0.80344549 0.95555363 1.001001  ]]


In [120]:
cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.55472493  0.83109952  0.03941888]
 [ 0.58988468 -0.35942826 -0.72308186]
 [ 0.58678473 -0.42436413  0.68963669]]

Eigenvalues 
[2.7211509  0.23682195 0.04503015]


In [121]:
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)


Eigenvectors 
[[ 0.55472493  0.83109952  0.03941888]
 [ 0.58988468 -0.35942826 -0.72308186]
 [ 0.58678473 -0.42436413  0.68963669]]

Eigenvalues 
[2.71842975 0.23658513 0.04498512]


In [125]:
cor_mat2 = np.corrcoef(newData.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat2)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.55472493  0.83109952  0.03941888]
 [ 0.58988468 -0.35942826 -0.72308186]
 [ 0.58678473 -0.42436413  0.68963669]]

Eigenvalues 
[2.71842975 0.23658513 0.04498512]


In [126]:
u,s,v = np.linalg.svd(X_std.T)
u

array([[-0.55472493,  0.83109952,  0.03941888],
       [-0.58988468, -0.35942826, -0.72308186],
       [-0.58678473, -0.42436413,  0.68963669]])

In [0]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))

In [128]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
2.7184297516795137
0.23658512768287968
0.044985120637608414


In [147]:
import plotly.plotly as py

tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

trace1 = dict(
    type='bar',
    x=['PC %s' %i for i in range(1,5)],
    y=var_exp,
    name='Individual'
)

trace2 = dict(
    type='scatter',
    x=['PC %s' %i for i in range(1,5)], 
    y=cum_var_exp,
    name='Cumulative'
)

data = [trace1, trace2]

layout=dict(
    title='Explained variance by different principal components',
    yaxis=dict(
        title='Explained variance in percent'
    ),
    annotations=list([
        dict(
            x=1.16,
            y=1.05,
            xref='paper',
            yref='paper',
            text='Explained Variance',
            showarrow=False,
        )
    ])
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename='selecting-principal-components')



ImportError: ignored